name: Deploy fib k8s gcp
on:
  push:
    branches:
      - main

env:
  SHA: $(git rev-parse HEAD) # Code SHA associé au commit

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Test
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t alexlionnel/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true alexlionnel/react-test npm test

      - name: Set Service Key
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GKE_SA_KEY }}'

      - name: Set Project
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: multi-338920

      - name: Auth
        run: |-
          gcloud --quiet auth configure-docker

      - name: Get Credentials
        uses: google-github-actions/get-gke-credentials@v0
        with:
          cluster_name: multi-cluster
          location: us-central1-c

      - name: Build
        run: |-
          docker build -t alexlionnel/fibonacci-client-k8s-gh:latest -t alexlionnel/fibonacci-client-k8s-gh:${{ env.SHA }} ./client
          docker build -t alexlionnel/fibonacci-server-k8s-pgfix:latest -t alexlionnel/fibonacci-server-k8s-pgfix:${{ env.SHA }} ./server
          docker build -t alexlionnel/fibonacci-worker-k8s-gh:latest -t alexlionnel/fibonacci-worker-k8s-gh:${{ env.SHA }} ./worker

      - name: Push
        run: |-
          docker push alexlionnel/fibonacci-client-k8s-gh:latest
          docker push alexlionnel/fibonacci-server-k8s-pgfix:latest
          docker push alexlionnel/fibonacci-worker-k8s-gh:latest
          
          docker push alexlionnel/fibonacci-client-k8s-gh:${{ env.SHA }}
          docker push alexlionnel/fibonacci-server-k8s-pgfix:${{ env.SHA }}
          docker push alexlionnel/fibonacci-worker-k8s-gh:${{ env.SHA }}

      - name: Apply
        run: |-
          kubectl apply -f k8s
          kubectl set image deployments/client-deployment client=alexlionnel/fibonacci-client-k8s-gh:${{ env.SHA }}
          kubectl set image deployments/server-deployment server=alexlionnel/fibonacci-server-k8s-pgfix:${{ env.SHA }}
          kubectl set image deployments/worker-deployment worker=alexlionnel/fibonacci-worker-k8s-gh:${{ env.SHA }}